version: "3.5"

services:
  react-app:
    image: keanthai/react:latest
    ports:
      - 6001:3000
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
  html-app:
    image: keanthai/htmlapp:latest
    ports:
      - 6002:80
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
  haproxy:
    image: keanthai/haproxy:latest
    ports:
      - 80:80
  # node-app:
  #   image: keanthai/node:latest
  #   ports:
  #     - 6003:8080
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  #     update_config:
  #       parallelism: 1
  #       order: start-first
  #       failure_action: rollback
  #     restart_policy:
  #       condition: on-failure
  
